package br.com.cardetail.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum PermissaoEnum {

    USUARIOS_VISUALIZAR("USUARIOS_VISUALIZAR"),
    USUARIOS_CRIAR("USUARIOS_CRIAR"),
    USUARIOS_EDITAR("USUARIOS_EDITAR"),
    USUARIOS_EXCLUIR("USUARIOS_EXCLUIR"),

    PERFIS_VISUALIZAR("PERFIS_VISUALIZAR"),
    PERFIS_CRIAR("PERFIS_CRIAR"),
    PERFIS_EDITAR("PERFIS_EDITAR"),
    PERFIS_EXCLUIR("PERFIS_EXCLUIR"),

    EMPRESA_VISUALIZAR("EMPRESA_VISUALIZAR"),
    EMPRESA_EDITAR("EMPRESA_EDITAR"),

    CLIENTES_VISUALIZAR("CLIENTES_VISUALIZAR"),
    CLIENTES_CRIAR("CLIENTES_CRIAR"),
    CLIENTES_EDITAR("CLIENTES_EDITAR"),
    CLIENTES_EXCLUIR("CLIENTES_EXCLUIR"),

    AGENDAMENTOS_VISUALIZAR("AGENDAMENTOS_VISUALIZAR"),
    AGENDAMENTOS_CRIAR("AGENDAMENTOS_CRIAR"),
    AGENDAMENTOS_EDITAR("AGENDAMENTOS_EDITAR"),
    AGENDAMENTOS_EXCLUIR("AGENDAMENTOS_EXCLUIR"),

    ORCAMENTOS_VISUALIZAR("ORCAMENTOS_VISUALIZAR"),
    ORCAMENTOS_CRIAR("ORCAMENTOS_CRIAR"),
    ORCAMENTOS_EDITAR("ORCAMENTOS_EDITAR"),
    ORCAMENTOS_EXCLUIR("ORCAMENTOS_EXCLUIR"),

    SERVICOS_VISUALIZAR("SERVICOS_VISUALIZAR"),
    SERVICOS_CRIAR("SERVICOS_CRIAR"),
    SERVICOS_EDITAR("SERVICOS_EDITAR"),
    SERVICOS_EXCLUIR("SERVICOS_EXCLUIR"),

    PACOTES_VISUALIZAR("PACOTES_VISUALIZAR"),
    PACOTES_CRIAR("PACOTES_CRIAR"),
    PACOTES_EDITAR("PACOTES_EDITAR"),
    PACOTES_EXCLUIR("PACOTES_EXCLUIR"),

    CADASTROS_VISUALIZAR("CADASTROS_VISUALIZAR"),
    CADASTROS_GERENCIAR("CADASTROS_GERENCIAR"),

    CONFIGURACAO_SISTEMA_GERENCIAR("CONFIGURACAO_SISTEMA_GERENCIAR"),

    SERVICOS_TERCEIRIZADOS_VISUALIZAR("SERVICOS_TERCEIRIZADOS_VISUALIZAR"),
    SERVICOS_TERCEIRIZADOS_CRIAR("SERVICOS_TERCEIRIZADOS_CRIAR"),
    SERVICOS_TERCEIRIZADOS_EDITAR("SERVICOS_TERCEIRIZADOS_EDITAR"),
    SERVICOS_TERCEIRIZADOS_EXCLUIR("SERVICOS_TERCEIRIZADOS_EXCLUIR"),

    AGENDAMENTOS_PAGAMENTOS_VISUALIZAR("AGENDAMENTOS_PAGAMENTOS_VISUALIZAR"),
    AGENDAMENTOS_PAGAMENTOS_CRIAR("AGENDAMENTOS_PAGAMENTOS_CRIAR"),
    AGENDAMENTOS_PAGAMENTOS_EXCLUIR("AGENDAMENTOS_PAGAMENTOS_EXCLUIR");

    private final String codigo;

    public static PermissaoEnum fromCodigo(final String codigo) {
        for (PermissaoEnum permissao : values()) {
            if (permissao.codigo.equals(codigo)) {
                return permissao;
            }
        }
        throw new IllegalArgumentException("Permissão não encontrada: " + codigo);
    }

}
